on:
  push:
    branches:
      - "**"
jobs:
  ubuntu-test:
    name: test on all operating systems
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: build and test
        run: |
          pip install -r requirements.txt
          python3 -m pytest --cov=symphony --cov-fail-under 100